name: Actions Setup Tests

on:
  pull_request:

jobs:
  setup-lando-os-test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-12
          - ubuntu-22.04
          # - windows-2022
        lando-version:
          # - '3.14.0'
          - '3-dev'
          # - 'stable'
        node-version:
          - '18'
        setup-string:
          - 1
          - auto
          - enabled
          - on
          - run
          - true
          - 0
          - false
          - off
          - disable
          - disabled
          - lando setup -y
          - lando setup --skip-common-plugins --plugin @lando/node --orchestrator 2.21.0 -y
          # these will fail
          # - lando.dev something
          # - oihywpihgklnw

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies and prepare
        run: |
          npm clean-install --prefer-offline --frozen-lockfile
          npm run prepare
      - name: Setup Lando version
        uses: ./
        with:
          lando-version: ${{ matrix.lando-version }}
          auto-setup: ${{ matrix.setup-string }}
          debug: true
          telemetry: false
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/core=latest

